name: Add Minister Witness IDs to Files

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: '0 0 * * *'

  workflow_dispatch:

jobs:
  update_ministers_with_witness_id:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Pull latest changes
      run: git pull

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas

    - name: Run the update script
      run: python add_minister_witness_id.py

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add output.csv minister.json
        git commit -m 'Update ministers with witness ID'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  filter_witness_meetings:
    runs-on: ubuntu-latest
    needs: update_ministers_with_witness_id

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Pull latest changes
      run: git pull

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas

    - name: Run the filter script
      run: python filter_witness_meetings.py

    - name: Commit and push filtered meetings
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add minister_parl_comm_deadlines.csv
        git commit -m 'Add filtered witness meetings output with disclosure deadline'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
