name: Flatten JSON to CSV

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  flatten-json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas

    - name: Run flatten_json.py
      run: |
        python flatten_json.py input.json output.csv

    - name: Cache output.csv
      uses: actions/cache@v2
      with:
        path: output.csv
        key: flatten-json-output
