name: Flatten JSON to CSV

on:
  workflow_dispatch:

jobs:
  flatten-json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas

    - name: Run flatten_json.py
      run: |
        python flatten_json.py minister.json output.csv

    - name: Commit output.csv
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add output.csv
        git commit -m 'Add output.csv'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
